### ISSUE TITLE
I am encountering an ANE evaluation error when running Dorado on macOS.

### ISSUE THREAD

**Issue by GanchimegNamuunbayar** [nanoporetech/dorado#1087]
# Issue Report

## Please describe the issue:

*Please provide a clear and concise description of the issue you are seeing and the result you expect.*

## Steps to reproduce the issue:

*Please list any steps to reproduce the issue.*

## Run environment:
- Dorado version:　0.8.0
- Dorado command:　dorado basecaller --batchsize 16 sup,4mC_5mC,6mA  ~/desktop/AA/pod5/ -r > ~/desktop/AA/bam/calls.bam
- Operating system: MacOS Sonoma 14.0
- Hardware (CPUs, Memory, GPUs): M2 Max, Memory 64GB
- Source data type (e.g., pod5 or fast5 - please note we always recommend converting to pod5 for optimal basecalling performance): multiple pod 5 files 
- Source data location (on device or networked drive - NFS, etc.): on device
- Details about data (flow cell, kit, read lengths, number of reads, total dataset size in MB/GB/TB): totaling 14GB (each 800MB to 4.5GB)
- Dataset to reproduce, if applicable (small subset of data to share as a pod5 to reproduce the issue):

## Logs

* Please provide output trace of dorado (run dorado with -v, or -vv on a small subset)

**Comment by HalfPhoton** [comment]
Hi @GanchimegNamuunbayar,
Can you add logs please?

**Comment by GanchimegNamuunbayar** [comment]
@HalfPhoton Sorry for the lack of information
command: dorado -vv basecaller --batchsize 16 sup,4mC_5mC,6mA ~/desktop/AA/pod5/ -r > ~/desktop/AA/bam/calls.bam
dorado:   0.8.0+acec121e
libtorch: 2.0.0
minimap2: 2.27-r1193

**Comment by HalfPhoton** [comment]
You've only added the version information here - The `-vv` flags must be placed after the sub-command: `dorado basecaller -vv` to generate detailed logs.

Kind regards,
Rich

**Comment by GanchimegNamuunbayar** [comment]
@HalfPhoton Thank you for the details.
I have tried it as you said 
command: dorado basecaller -vv --batchsize 16 sup,4mC_5mC,6mA ~/desktop/pod5/ -r > ~/desktop/bam/calls.bam

The last lines before the computer shut down were:
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer PCR_PSK_rev1
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer PCR_PSK_rev2
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer cDNA_VNP
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer cDNA_SSP
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer PCS110_forward
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer PCS110_reverse
[2024-10-22 17:42:51.715] [trace] Checking adapter/primer RAD

**Comment by HalfPhoton** [comment]
Could you please write the logs to a file and share them? These last few lines aren't enough for us to see the issue.

```bash
dorado basecaller -vv --batchsize 16 sup,4mC_5mC,6mA ~/desktop/pod5/ -r > ~/desktop/bam/calls.bam 2> dorado.trace
```

Kind regards,
Rich

**Comment by HalfPhoton** [comment]
Does you issue persist with dorado 0.8.2? It has a number of bug fixes which might be causing your crash.

**Comment by HalfPhoton** [comment]
Hi @GanchimegNamuunbayar,

For some reason I can't view these logs, can you create a ticket on the ONT customer support page please? 
We can then get these large log files and help you from there.

Please reference this GitHub issue and the great people at customer support will be able to get this information to me. 

Kind regards,
Rich

**Comment by malton-ont** [comment]
@HalfPhoton I've fixed the link for @GanchimegNamuunbayar, logs should be accessible now.

**Comment by GanchimegNamuunbayar** [comment]
Hi @HalfPhoton ,
I hope you're doing well! It's been a while since I shared the logs, and I just wanted to check in and see if there have been any updates or if you’ve had a chance to review them. Looking forward to your reply.
Thank you again for your support!

Also thanks to @malton-ont for kindly fixing the link earlier—really appreciate the help!!

Best,
Ganchimeg

**Comment by malton-ont** [comment]
Hi @GanchimegNamuunbayar,

dorado-0.8.3 was released yesterday and contains a couple of fixes for SUP basecalling on Apple silicon - could you give this a try?

**Comment by GanchimegNamuunbayar** [comment]
@malton-ont 
I tried it, but the error persists. Are there others facing the same problem? Could it be related to something in my environment or command?
