### ISSUE TITLE
Adapter trimming issues in RNA002 and RNA004 models

### ISSUE THREAD

**Issue by DepledgeLab** [nanoporetech/dorado#540]
Hello,

I ran Dorado on an RNA002 dataset to compare the output with Guppy but observed that I get the same results in terms of read length distributions, regardless of whether I use the --no-trim or --trim adapters flags? This does not make sense to me unless (i) the --no-trim flag is not working or (ii) trimming is not taking place in either case. 

`
/project/sysviro/dorado-0.5.0-linux-x64/bin/dorado basecaller --no-trim -r $MODEL/rna002_70bps_hac@v3 $IN/UNINF_18h-1/20230703_0909_MN32174_FAH74927_8f149cea/pod5/ > $OUT/UNINF_18h-1.hac.notrim.dorado.0.5.0.bam

/project/sysviro/dorado-0.5.0-linux-x64/bin/dorado basecaller --trim adapters -r $MODEL/rna002_70bps_hac@v3 $IN/UNINF_18h-1/20230703_0909_MN32174_FAH74927_8f149cea/pod5/ > $OUT/UNINF_18h-1.hac.trimAdapter.dorado.0.5.0.bam
`

Based on the comparison with Guppy v6.5.7 (without trimming), I would interpret the results as showing that Dorado is trimming in all cases, regardless of the flag being set?

Could you please clarify and let me know how I can prevent any trimming?

![trimming](https://github.com/nanoporetech/dorado/assets/32496778/6ccd541b-9bf0-4103-9b63-4830ab7ec185)

**Comment by tijyojwad** [comment]
Hi @DepledgeLab - adapter trimming is enabled by default for RNA002 and RNA004 and can't be disabled right now. We're updating our documentation which will clarify that, apologies for that.

What's your use case for keeping RNA adapters in tact?

**Comment by DepledgeLab** [comment]
Ok, that is definitely a significant problem for us. We are using the sequence specific (i.e. targeted) RNA002 and RNA004 direct RNA Sequencing approaches and have found, at least with guppy + trimming, the many reads are over-trimmed or under-trimmed and that the best outputs are actually obtained without any trimming i.e. relying on soft-clipped alignments to solve the problem (which it does). We want to be able to do the same with Dorado and the RNA004 chemistry.

Can you offer a workable solution for this as it is putting a set of important projects at risk?

**Comment by tijyojwad** [comment]
Thanks for the details! Are you seeing the same over/under trimming with dorado as well?

**Comment by DepledgeLab** [comment]
Yes, very much the same (massive overtrimming) with Dorado on the RNA002 data. For RNA004 I don't have an untrimmed dataset for comparison (hence the issue) but I suspect the same based on observed read length distributions and coverage plots.

Overprinting is definitely the big issue, underwriting is (as you indicated) handled by soft clipping.

**Comment by tijyojwad** [comment]
Hi @DepledgeLab - we just released v0.5.1 (https://github.com/nanoporetech/dorado#installation) which skips RNA adapter trimming when the `--no-trim` option is passed to the basecaller.

**Comment by DepledgeLab** [comment]
Hello again. 

I've been trying out the new version of dorado by applying --no-trim or --trim adapters to my datasets but the results appear virtually identical, suggesting to me that trimming is still occuring even when --no-trim is applied. 

After running dorado, I generated sequencing_summary reports and looked up a bunch of reads in the two different outputs but they all had exactly the same sequence_length_template.

**Comment by tijyojwad** [comment]
Hi @DepledgeLab - I checked again on a few datasets and the `--no-trim` option is working as expected. i.e. when `--no-trim` is supplied vs not supplied, I'm seeing difference in read lengths.

I think the trimming algorithm isn't able to find the trim point correctly in your reads, and as a result isn't applying any trimming at all.

If you run `dorado` with `-vv`, it'll run in trace mode. The debug output will have lines that look like this
```
[trace] ScalerNode: 0025688f-9a7d-4b5d-8df4-819dadf33570 shift: 783.36 scale: 112.1 trim: 2650
```

if `trim` > 0, that means some adapter trimming is happening. Can you check with your dataset?

P.S. I would run this with a subset of the reads as there's a lot of debug output. you can do that with `--max-reads N` to basecall only N reads from your dataset.

**Comment by DepledgeLab** [comment]
Hi @tijyojwad,

Thanks for the quick response. I did as you suggested and checked 10k reads. The output looks like what follows:

[2024-01-03 15:39:04.202] [trace] ScalerNode: 3c1b268d-46e0-4116-a75e-ff56023d3a23 shift: 352.32 scale: 113.28 trim: 0
[2024-01-03 15:39:04.202] [trace] window 1000-1250 min 0 max 366 diff 366
[2024-01-03 15:39:04.202] [trace] window 1050-1300 min 0 max 366 diff 366
[2024-01-03 15:39:04.202] [trace] window 1100-1350 min 0 max 366 diff 366
[2024-01-03 15:39:04.202] [trace] window 1150-1400 min 0 max 366 diff 366
[2024-01-03 15:39:04.202] [trace] window 1200-1450 min 353 max 366 diff 13
[2024-01-03 15:39:04.203] [trace] window 2900-3150 min 401 max 452 diff 51
[2024-01-03 15:39:04.203] [trace] window 2950-3200 min 410 max 452 diff 42
[2024-01-03 15:39:04.203] [trace] ScalerNode: 3c4369f6-81dc-4f46-b846-5f5d0eb9c275 shift: 339.84 scale: 82.6 trim: 0

Certainly it looks like trimming is not happening which suggests the algorithm isnt able to find the trim point. I assume this is due to the lack of poly(A) tails in the RNA we have sequenced  (we are using a variant of the sequence specific protocol) but I am surprised that guppy is able to trim at least some of the reads (20-30%) correctly while dorado can't trim any?

**Comment by tijyojwad** [comment]
Yep I'm surprised as well that it's not able to find any either. It shouldn't have anything to do with polyA per se, since we look at some signal level changes in the detection algorithm. It's a different implementation than what's in guppy.

Do you see this with both RNA002 and RNA004? Would you be comfortable sharing a pod5 with 1 or 2 of the reads for each for us to look at?

**Comment by DepledgeLab** [comment]
[FAX71798_pass_e0fcb524_b665e3ce_258.zip](https://github.com/nanoporetech/dorado/files/13827513/FAX71798_pass_e0fcb524_b665e3ce_258.zip)

Good morning,

I've attached one of the pod5 files from the RNA004 run here. Hopefully this will be of help.

**Comment by tijyojwad** [comment]
Thank you @DepledgeLab - I will have a look at these reads

**Comment by tijyojwad** [comment]
I've taken an initial look at the data. The reads are quite short, and a lot of them look like they're only adapter data (which is why doesn't couldn't determine a trim point since the whole read looks like Ana adapter). however, some of the reads do look fine, but the data is quite noisy. I think we can update our adapter heuristics to address those cases!

**Comment by DepledgeLab** [comment]
Thanks for the update. I'm surprised you are seeing so many apparent adaptor only reads as when we align the output against our target genome we get a very high alignment rate (>95%). I'm still going through this to see if any of this can be explained by misalignment of adapter-only sequences but I would be surprised if this is the case.

As an aside, can you confirm how long you expect the adapter sequences to be (RTA + RMX)?
